### ISSUE TITLE
Dynamic Coordinates

### ISSUE THREAD

**Issue by nfssdq** [arsho/t_rex_bot#2]
Coordinates doesn't work on different screen size.

**Comment by arsho** [comment]
Yeah, I noticed. May be searching the black dot in the screen region? Like below:
```
pos = pyautogui.locateCenterOnScreen(imPath('b.png'), region=GAME_REGION)
        if pos != None:
            pyautogui.press("space")
```

**Comment by nfssdq** [comment]
i am searching for the t rex in the image. that is the left end. and notice when the game starts there is a "HI" at the top, i am marking it as right end. top and bottom can be derived from these also.
